version: '3.8'

services:
  survey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: intersection-safety_container
    hostname: 0.0.0.0
    restart: always
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/gvanwijnen/survey-intersection-safety/database.db:/wd/database.db
      # Mount the images directory at runtime if needed
      # - /data/images:/wd/assets/images
    networks:
      - survey_network

networks:
  survey_network:
    driver: bridge